# -*- mode: ruby -*-
# vi: set ft=ruby :

# Vagrantfile API/syntax version. Don't touch unless you know what you're doing!
VAGRANTFILE_API_VERSION = "2"

boxes = [
         {:name => "c6401", :ipaddress => "192.168.64.101", :roles => ["base", "ambari"], :recipes => [], :json => {}},
         {:name => "c6402", :ipaddress => "192.168.64.102", :roles => ["base"], :recipes => [], :json => {}},
         {:name => "c6403", :ipaddress => "192.168.64.103", :roles => ["base"], :recipes => [], :json => {}},
         {:name => "c6404", :ipaddress => "192.168.64.104", :roles => ["base"], :recipes => [], :json => {}},
         {:name => "c6405", :ipaddress => "192.168.64.105", :roles => ["base"], :recipes => [], :json => {}},
         {:name => "c6406", :ipaddress => "192.168.64.106", :roles => ["base"], :recipes => [], :json => {}},
         {:name => "c6407", :ipaddress => "192.168.64.107", :roles => ["base"], :recipes => [], :json => {}},
         {:name => "c6408", :ipaddress => "192.168.64.108", :roles => ["base"], :recipes => [], :json => {}},
         {:name => "c6409", :ipaddress => "192.168.64.109", :roles => ["base"], :recipes => [], :json => {}},
         {:name => "c6410", :ipaddress => "192.168.64.110", :roles => ["base"], :recipes => [], :json => {}},
]

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|
  config.hostmanager.enabled = true
  config.hostmanager.manage_host = true
  config.hostmanager.ignore_private_ip = false
  config.hostmanager.include_offline = true

  boxes.each do |opts|
    config.vm.define opts[:name] do |vmconfig|
      # CentOS 6.4 x86_64 Minimal (VirtualBox Guest Additions 4.2.12, Chef 11.4.4, Puppet 3.1.1)
      vmconfig.vm.box = "centos6.4"
      vmconfig.vm.box_url = "http://developer.nrel.gov/downloads/vagrant-boxes/CentOS-6.4-x86_64-v20130427.box"

      vmconfig.vm.provider :virtualbox do |vb|
        vb.customize ["modifyvm", :id, "--memory", 512] # RAM allocated to each VM
      end

      # uncomment the line below to set up the ambari dev environment
      # vmconfig.vm.provision :shell, :path => "dev-bootstrap.sh"

      vmconfig.vm.hostname = "%s.vagrant" % opts[:name].to_s
      vmconfig.vm.network :private_network, ip: opts[:ipaddress]

      vmconfig.vm.provision :chef_solo do |chef|
        chef.cookbooks_path = ["cookbooks", "site-cookbooks"]
        chef.data_bags_path = "databags"
        chef.roles_path = "roles"

        opts[:roles].each do |role|
          chef.add_role(role)
        end

        opts[:recipes].each do |recipe|
          chef.add_recipe(recipe)
        end
      end
    end
  end
end
